Breadth-First-Search/swapd

- server/db/models/index.js
- server/db/models/interest.js
- server/db/models/message.js
- server/db/models/review.js
- server/db/models/service.js
- server/db/models/serviceCategory.js
- server/db/models/swap.js
- server/db/models/user.js
- server/index.js
> chore: added models

- server/algorithm.js
> added in algorithm

- script/seed.js
- script/seedGenerator.js
- script/seedGenerator.spec.js
- server/algorithm.js
- server/db/models/message.js
- server/db/models/user.js
- server/index.js
> synced up algorithm interest randomizer with seed.js

- server/api/users.js
- server/index.js
> search user by service name route working

- script/seedGenerator.js
- server/db/models/user.js
> addtional seed sync and zipCode edit

- server/db/models/user.js
> added overall rating field in users table

- script/seedGenerator.js
- server/algorithm.js
- server/api/users.js
- server/db/models/service.js
> got algorithm working on routes

- client/components/navbar.js
- public/style.css
> feature: submitting a search will push history to /search//query

- client/components/SearchResults.js
- client/components/SearchResultsTile.js
- client/components/index.js
- client/routes.js
> partially working results page

- client/components/SearchResults.js
- client/components/navbar.js
- client/routes.js
> able to search for specific skill and return sorted results

- client/components/SearchResultsTile.js
- client/components/navbar.js
> minor edits

- server/api/users.js
> adjusted syntax errors

- client/components/navbar.js
- public/style.css
> modified navbar

- client/components/interests.js
- client/components/user-profile-edit.js
- client/store/interests.js
> updates to profile edit

- client/components/SelectedService.js
- client/components/SelectedUserProfile.js
- client/routes.js
- client/store/index.js
- client/store/user.js
SelectedUserProfile Component
- User can access this page from Selected Service Component
- User can also access through "/user-profile/:userId"
- CDM: gets selected user's info, services, and interests
- Renders the same details as user-profile component without the edit profile capability
> Created SelectedUserProfile Component

- client/components/Services.js
- client/components/interests.js
- client/store/interests.js
- client/store/services.js
- server/api/services.js
- server/api/users.js
> Chore: Add new service, Update Add new interest

- client/components/SelectedService.js
- client/components/SwapList.js
- script/seed.js
- server/api/swaps.js
- server/db/models/index.js
- server/db/models/swap.js
- Can now make duplicate swaps with swapId as the unique identifier.
> Database update

- client/components/user-profile-edit.js
- script/seed.js
- script/seedGenerator.js
- server/db/models/index.js
> calculates average and sets average each time a review is created. also big randomized review seed.

- client/components/MessagesList.js
- client/components/NewMessageEntry.js
- client/components/OfferForm.js
- script/seed.js
- server/api/messages.js
- server/db/models/index.js
- server/db/models/message.js
- server/db/models/service.js
- server/db/models/user.js
> Offer render

- script/seed.js
- server/db/models/index.js
> couple of seed fixes

- client/components/InitiateSwapButton.js
> added alerts and pushes user to the swap messages page

- client/store/user.js
- script/seed.js
> updated seed

- client/components/Reviews.js
- client/components/home-page.js
- client/store/index.js
- client/store/reviews.js
- server/api/index.js
- server/api/reviews.js
- server/api/swaps.js
- server/api/users.js
- server/db/models/swap.js
> chore: add review component and routes

- client/components/MessagesList.js
- client/components/NewMessageEntry.js
- client/components/OfferForm.js
- client/socket.js
- client/store/messages.js
- server/api/messages.js
- server/api/swaps.js
- server/socket/index.js
> you can send offers now

- client/components/SearchResultsTile.js
- client/components/home-page.js
- server/db/models/index.js
> homepage setup

- client/components/SelectedService.js
- public/style.css
- script/seedGenerator.js
- server/api/services.js
- server/db/models/index.js
> updated review table to associate with user

- client/components/TopTen.js
- client/components/home-page.js
> Added grid display for top 10 users in homepage

- client/components/SelectedService.js
- server/api/services.js
- server/db/models/index.js
> eager loads and maps reviews per service

- client/components/InitiateSwapButton.js
- client/components/MessagesList.js
- client/components/OfferForm.js
- client/store/messages.js
- script/seed.js
- server/api/swaps.js
- server/db/models/index.js
- server/db/models/message.js
- server/db/models/swap.js
> confirming swaps works jankily

- client/components/MessagesList.js
- public/style.css
- script/seedGenerator.js
> styling and seed fixes

- client/components/Reviews.js
- public/style.css
> style updates

- client/components/SelectedUserProfile.js
- client/components/TopTen.js
- server/db/models/service.js
- server/db/models/user.js
> optimized matching interests also added Link to top users

- client/components/TopTen.js
- script/seedGenerator.js
- server/db/models/index.js
> quick styling and seed fixes

- client/components/Services.js
- client/store/services.js
- server/api/interests.js
- server/api/services.js
> sorted service adding no repeats

- client/components/Message.js
- client/components/MessagesList.js
- client/components/Reviews.js
- client/components/UserProfile.js
- public/index.html
- public/style.css
> stars on reviews

- client/components/MessagesList.js
- client/components/OfferForm.js
- client/components/SelectedUserProfile.js
- public/style.css
- server/api/messages.js
Styled chat and current offer and confirmed swap.
> styled message form and chat container

- client/components/OfferForm.js
- client/components/SearchResults.js
- server/api/searchAlgorithm.js
- server/api/users.js
> search kinda works

- client/components/Reviews.js
- server/api/reviews.js
> star ratings work

- client/components/UserProfile.js
> finished styling for users own page

- client/components/SelectedService.js
- client/components/SelectedUserProfile.js
- public/style.css
- server/api/services.js
> styling completed for selected service page

- client/components/InitiateSwapButton.js
> edit to swap request text

- client/components/SearchResults.js
- server/algorithm.js
> search res fix

- client/components/SelectedUserProfile.js
> users have the correct number of stars

- client/components/SearchResults.js
- client/components/SearchResultsTile.js
> quick bug fixes

- client/components/home-page.js
- server/db/models/user.js
> bug fixes to models for oauth

- client/store/interests.js
- server/api/messages.js
- server/api/swaps.js
- server/api/users.js
> Chore: Edit routes

- client/components/MessagesList.js
- client/socket.js
- client/store/messages.js
- server/socket/index.js
> 1 to 1 chat works

- client/components/SelectedService.js
- client/components/SwapList.js
- public/style.css
> ordered swap list and changed status color

- client/components/NewUserService.js
- package-lock.json
- package.json
- public/style.css
- server/api/users.js
> styled page and added skill rating and remote choice

- client/components/SwapList.js
- script/seedGenerator.js
> added image urls for seed data

- client/components/UserProfile.js
- public/style.css
> add styling

- client/components/navbar.js
- script/seedGenerator.js
> seed data update

- client/components/navbar.js
- server/api/searchAlgorithm.js
- server/api/users.js
> better search

- server/api/users.js
> fixed search bug

- client/components/InitiateSwapButton.js
- client/components/SelectedService.js
> message bug
